# Generated by Django 6.0 on 2025-12-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='test.png', upload_to='image'),
            preserve_default=False,
        ),
    ]
